site_name: Rocket Learning Rewards
site_url: https://rey-rocket.github.io/Rocket-Docs/
site_description: Fuel Engagement. Reward Progress. Drive Success.
site_author: Rocket Education Rewards

# Repository
repo_url: https://github.com/rey-rocket/Rocket-Docs
repo_name: rey-rocket/Rocket-Docs
edit_uri: edit/main/docs/

# Theme Configuration - Enhanced Navigation
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  font:
    text: Poppins
    code: Roboto Mono
  
  # Navigation Features - Cedar-inspired layout
  features:
    # Navigation Structure
    - navigation.tabs           # Top-level sections as tabs
    - navigation.tabs.sticky    # Keep tabs visible when scrolling
    - navigation.sections       # Group subsections in sidebar
    - navigation.expand         # Auto-expand all subsections
    - navigation.indexes        # Enable section index pages
    - navigation.top            # Back-to-top button
    - navigation.footer         # Next/previous navigation
    - navigation.instant        # Instant loading
    - navigation.tracking       # Track page sections in URL
    
    # Table of Contents
    - toc.follow               # TOC follows scroll
    
    # Search Features
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search terms
    - search.share             # Share search results
    
    # Content Features
    - content.code.copy        # Copy code button
    - content.code.annotate    # Code annotations
    - content.footnote.tooltips # Footnote tooltips
    - content.tabs.link        # Link content tabs
    - content.action.edit      # Edit button on pages
    - content.action.view      # View source button
    
  palette:
    - scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Navigation - Cedar-inspired organization
nav:
  - Home: index.md
  
  - Quick Start:
      - Getting Started: getting-started/index.md
      - How It Works: getting-started/how-it-works.md
      - Requirements: getting-started/requirements.md
      - First Steps: getting-started/first-steps.md
      - Partner Qualification: getting-started/partner-qualification.md
  
  - Setup & Configuration:
      - Configuration: configuration/index.md
      - Points & Activities: configuration/points-activities.md
      - Rewards System: configuration/rewards-system.md
      - AI Insights: configuration/ai-insights.md
      - Roles & Permissions: configuration/roles-permissions.md
  
  - Integrations:
      - LMS Integrations: integrations/index.md
      - Moodle: integrations/moodle.md
      - Canvas: integrations/canvas.md
      - Open LMS: integrations/olms.md
      - LearnWorlds: integrations/learnworlds.md
      - Custom Integrations: integrations/custom-integrations.md
  
  - Implementation:
      - Implementation Guide: implementation/index.md
      - Account Setup: implementation/account-setup.md
      - LMS Integration: implementation/lms-integration.md
      - Testing: implementation/testing.md
      - Go Live: implementation/go-live.md
  
  - Analytics & Insights:
      - Analytics: analytics/index.md
      - Dashboards: analytics/dashboards.md
      - Success Metrics: analytics/success-metrics.md
      - Customer Success: analytics/customer-success.md
      - Financial Reporting: analytics/financial-reporting.md
  
  - User Guides:
      - For Administrators: user-guides/administrators.md
      - For Instructors: user-guides/instructors.md
      - For Students: user-guides/students.md
  
  - Success Stories:
      - Case Studies: case-studies/index.md
      - Corporate Training: case-studies/corporate-training.md
      - International School: case-studies/international-school.md
      - University Excellence: case-studies/university-excellence.md
  
  - Developer Resources:
      - API Documentation: reference/api-reference.md
      - Authentication: reference/authentication.md
      - Webhooks: reference/webhooks.md
      - Error Codes: reference/error-codes.md
      - Data Security: Data Security/data-security.md
  
  - Support & Resources:
      - Support: support/index.md
      - FAQ: support/faq.md
      - Troubleshooting: support/troubleshooting.md
      - Downloads: support/downloads.md
      - Contact: support/contact.md
      - Roadmap: Roadmap/roadmap.md

# Markdown Extensions - Optimized for Cedar content
markdown_extensions:
  # Basic extensions
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr
  
  # Table of contents
  - toc:
      permalink: "🚀"
      toc_depth: 3
      title: On this page
  
  # PyMdown extensions
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

# Custom CSS & JavaScript - Cedar-Inspired Styling
extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap

extra_javascript:
  - assets/js/custom.js

# Footer & Social
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/rocket-education-rewards
      name: Follow us on LinkedIn
    - icon: fontawesome/brands/twitter  
      link: https://twitter.com/rocketeducation
      name: Follow us on Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:support@rocketeducationrewards.com
      name: Email Support
    - icon: fontawesome/solid/phone
      link: tel:+44-800-ROCKET-1
      name: Call Support
  
  generator: false  # Remove "Made with Material for MkDocs"
  
  # Custom footer content
  status:
    new: Recently added
    deprecated: Deprecated

copyright: |
  Copyright &copy; 2025 <a href="https://rocketeducationrewards.com" target="_blank">Rocket Education Rewards</a><br>
  <span style="font-size: 0.8em;">Fuel Engagement. Reward Progress. Drive Success.</span>
