site_name: Rocket Learning Rewards
site_url: https://rey-rocket.github.io/Rocket-Docs/
site_description: Fuel Engagement. Reward Progress. Drive Success.

# Theme Configuration - Left Navigation Style
theme:
  name: material
  custom_dir: overrides/  # For custom templates
  
  palette:
    - scheme: default
      primary: custom
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: orange  
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Inter
    code: JetBrains Mono
  
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  
  features:
    # LEFT SIDEBAR NAVIGATION (remove tabs)
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    
    # SEARCH & CONTENT FEATURES
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    
    # ENHANCED UX
    - header.autohide
    - toc.follow
    - toc.integrate

# LEFT SIDEBAR NAVIGATION STRUCTURE
nav:
  - Home: 
    - index.md
    - Why Choose Rocket: why-rocket.md
    - Success Stories:
      - Overview: case-studies/index.md
      - Universities: case-studies/university-excellence.md
      - Corporate Training: case-studies/corporate-training.md
      - Schools: case-studies/international-school.md
  
  - Getting Started:
    - Quick Start: getting-started/index.md
    - Overview: getting-started/overview.md
    - Implementation Timeline: getting-started/timeline.md
    - Pre-Requirements: getting-started/requirements.md
    - Your Success Team: getting-started/support-team.md
  
  - Implementation:
    - Overview: implementation/index.md
    - Technical Setup: implementation/technical-setup.md
    - Student Onboarding: implementation/student-onboarding.md
    - LMS Integration: implementation/lms-integration.md
    - Testing & Go-Live: implementation/testing.md

  - User Guides:
    - Administrators: user-guides/administrators.md
    - Instructors: user-guides/instructors.md
    - Students: user-guides/students.md
  
  - Strategy & Configuration:
    - Overview: strategy/index.md
    - Gamification Strategy: strategy/gamification.md
    - Points & Activities: strategy/points-activities.md  
    - Reward System: strategy/rewards.md
    - Academic Best Practices: strategy/academic-practices.md
  
  - Analytics & Optimisation:
    - Overview: analytics/index.md
    - Performance Dashboards: analytics/dashboards.md
    - Success Metrics: analytics/metrics.md
    - ROI Measurement: analytics/roi.md
    - Continuous Improvement: analytics/optimisation.md
  
  - Support & Resources:
    - Get Help: support/index.md
    - Troubleshooting: support/troubleshooting.md
    - FAQ: support/faq.md
    - Contact Us: support/contact.md
    - Downloads: support/downloads.md

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: "🚀"
      toc_depth: 3

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

# Custom CSS & JavaScript - Website Styling
extra_css:
  - assets/css/rocket-theme.css
  - assets/css/components.css  
  - assets/css/animations.css
  #- https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap

extra_javascript:
  - assets/js/rocket-interactions.js
  - assets/js/analytics.js

# Footer & Social
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/rocket-education-rewards
      name: Follow us on LinkedIn
    - icon: fontawesome/brands/twitter  
      link: https://twitter.com/rocketeducation
      name: Follow us on Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:support@rocketeducationrewards.com
      name: Email Support
    - icon: fontawesome/solid/phone
      link: tel:+44-800-ROCKET-1
      name: Call Support
  
  generator: false  # Remove "Made with Material for MkDocs"
  
  # Custom footer content
  status:
    new: Recently added
    deprecated: Deprecated

copyright: |
  Copyright &copy; 2025 <a href="https://rocketeducationrewards.com" target="_blank">Rocket Education Rewards</a><br>
  <span style="font-size: 0.8em;">Fuel Engagement. Reward Progress. Drive Success.</span>
