site_name: Rocket Learning Rewards
site_url: https://rey-rocket.github.io/Rocket-Docs/
site_description: Fuel Engagement. Reward Progress. Drive Success.

# Theme Configuration - Left Navigation Style
theme:
  features:
    - content.footnote.tooltips

  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Poppins
    code: Roboto Mono
  palette:
    - scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - How It Works: getting-started/how-it-works.md
      - Requirements: getting-started/requirements.md
      - First Steps: getting-started/first-steps.md
      - Partner Qualification: getting-started/partner-qualification.md
  - Configuration:
      - Overview: configuration/index.md
      - Points & Activities: configuration/points-activities.md
      - Rewards System: configuration/rewards-system.md
      - AI Insights: configuration/ai-insights.md
      - Roles & Permissions: configuration/roles-permissions.md
  - Integrations:
      - Overview: integrations/index.md
      - Moodle: integrations/moodle.md
      - Canvas: integrations/canvas.md
      - Open LMS: integrations/olms.md
      - LearnWorlds: integrations/learnworlds.md
      - Custom Integrations: integrations/custom-integrations.md
  - Implementation:
      - Overview: implementation/index.md
      - Account Setup: implementation/account-setup.md
      - LMS Integration: implementation/lms-integration.md
      - Testing: implementation/testing.md
      - Go Live: implementation/go-live.md
  - Analytics:
      - Overview: analytics/index.md
      - Dashboards: analytics/dashboards.md
      - Success Metrics: analytics/success-metrics.md
      - Customer Success: analytics/customer-success.md
      - Financial Reporting: analytics/financial-reporting.md
  - User Guides:
      - Administrators: user-guides/administrators.md
      - Instructors: user-guides/instructors.md
      - Students: user-guides/students.md
  - Case Studies:
      - Overview: case-studies/index.md
      - Corporate Training: case-studies/corporate-training.md
      - International School: case-studies/international-school.md
      - University Excellence: case-studies/university-excellence.md
  - API Reference:
      - API Documentation: reference/api-reference.md
      - Authentication: reference/authentication.md
      - Webhooks: reference/webhooks.md
      - Error Codes: reference/error-codes.md
  - Support:
      - Overview: support/index.md
      - FAQ: support/faq.md
      - Troubleshooting: support/troubleshooting.md
      - Downloads: support/downloads.md
      - Contact: support/contact.md
  - Data Security: Data Security/data-security.md
  - Roadmap: Roadmap/roadmap.md

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: "🚀"
      toc_depth: 3

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

# Custom CSS & JavaScript - Cedar-Inspired Styling
extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap
  - https://fonts.googleapis.com/icon?family=Material+Icons

extra_javascript:
  - assets/js/custom.js

# Footer & Social
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/rocket-education-rewards
      name: Follow us on LinkedIn
    - icon: fontawesome/brands/twitter  
      link: https://twitter.com/rocketeducation
      name: Follow us on Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:support@rocketeducationrewards.com
      name: Email Support
    - icon: fontawesome/solid/phone
      link: tel:+44-800-ROCKET-1
      name: Call Support
  
  generator: false  # Remove "Made with Material for MkDocs"
  
  # Custom footer content
  status:
    new: Recently added
    deprecated: Deprecated

copyright: |
  Copyright &copy; 2025 <a href="https://rocketeducationrewards.com" target="_blank">Rocket Education Rewards</a><br>
  <span style="font-size: 0.8em;">Fuel Engagement. Reward Progress. Drive Success.</span>
